### ISSUE TITLE
 case class Fusion: podría ser una nueva Especie en vez de un Movimiento

### ISSUE THREAD

**Issue by bordio** [marvelek/tadp-2015c2-tp-objetos-funcional#9]
una fusión es un Guerrero nuevo, por lo que Fusion puede ser una Especie

**Comment by bordio** [comment]
Es verdad! jaja

**Comment by bordio** [comment]
@canofm , en el branch que creaste hoy pusiste un trait Fusionable.. eso es para validar nomás? Es decir, validar si puede, o no, fusionarse alguien según su especie? 
Si es así, faltaría en esa solución la especie "Fusión", que como Marcos bien dice, es la que se llama "Indefinido". Estoy en lo correcto?
Si es así, entonces me parece bien cambiarle el nombre de Indefinido a Fusión, y agregar el trait Fusionable al branch de correcciones.

**Comment by marvelek** [comment]
Me sumo a la pregunta de Orne sobre para que el trait. Así como por ejemplo
en cargarki es cargar ki quien decide quien carga y como carga, no debería
ser igual en fusion? Que el mismo movimiento se encargue de ver si se
pueden o no fusionar
